@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit - Dynamic System Builder"
echo Setting main branch...
git branch -M main
echo Adding remote repository...
git remote add origin https://github.com/AniketChakraborty798/Dynamic-System-Builder.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
